---

- hosts: all
  gather_facts: true
  connection: smart

  tasks:
    - name: "DISK | Create a partition for the added disk space"
      expect:
        command: /sbin/fdisk /dev/sda
        responses:
          'Command \(m for help\):':
            - 'n'
            - 't'
            - 'w'
          'Select \(default.*$': 'p'
          'Partition number.*$': "{{ next_part }}"
          'First sector.*$': "\n"
          'Last sector.*$': "\n"
          'Hex code.*$': '08e'
        echo: yes
      ignore_errors: yes
      register: fdisker

    - name: "PRINT | fdisker output"
      debug:
        msg: "{{ fdisker.stdout }}"

    - name: "DISK | Scan for new disk space"
      command: partprobe -s

    - name: "DISK | Create a physical volume on the new space with LVM"
      command: pvcreate /dev/sda{{ next_part }}
      ignore_errors: yes

    - name: "DISK | Extend the volume group with LVM"
      command: vgextend rhel /dev/sda{{ next_part }}
      ignore_errors: yes

    - name: "DISK | Extend the logical volume with LVM"
      command: lvextend -L{{ item.size }} {{ item.part }}
      with_items: "{{ mount }}"
      ignore_errors: yes

    - name: "DISK | Grow the file system into the new space"
      command: xfs_growfs -d {{ item.part }}
      with_items: "{{ mount }}"
